version: '3.7'

services:
  mariadb: 
    container_name: "mariadb"
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes: 
      - v_maria:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: "wordpress"
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - v_wp:/var/www/html
    networks:
      - inception
    restart: always

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    depends_on:
      - wordpress
    volumes:
      - v_wp:/var/www/html
    networks:
      - inception
    ports:
      - 443:443
    restart: always

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  v_wp:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gcollet/data/html

  v_maria:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/gcollet/data/mysql
